#!/bin/bash
set -eo pipefail

# Update the -advertise address based on the interface that ContainerPilot
# has been told to listen on.
preStart() {
    if [ ! -e /etc/krb5kdc/principal ]; then
        _log "Generating KDC Master Key"
        kdb5_util -P $KERB_MASTER_KEY -r $REALM create -s
    fi
    if [ ! -e /etc/krb5kdc/kadm5.acl ]; then
        _log "Generating admin principal"
        kadmin.local -q "addprinc -pw $KERB_ADMIN_PASS $KERB_ADMIN_USER/admin"
        echo "*/admin@$REALM *" > /etc/krb5kdc/kadm5.acl
    fi

    exit 0
}

kdcHealth() {
    _log "No kdc health method implemented"
    exit 0
}

kdcMasterHealth() {
    _log "No kdc-master health method implemented"
    exit 0
}

kadminHealth() {
    _log "No kadmin health method implemented"
    exit 0
}

kpasswdHealth() {
    _log "No kpasswd health method implemented"
    exit 0
}


_log() {
    echo "kerberos: $@"
}

# ---------------------------------------------------
# parse arguments

# Get function list
funcs=($(declare -F -p | cut -d " " -f 3))

until
    if [ ! -z "$1" ]; then
        # check if the first arg is a function in this file, or use a default
        if [[ " ${funcs[@]} " =~ " $1 " ]]; then
            cmd=$1
            shift 1
        fi

        $cmd "$@"
        if [ $? == 127 ]; then
            help
        fi

        exit
    else
        health
    fi
do
    echo
done
